import Config

# We include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :bonfire, Bonfire.Web.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :logger,
  backends: [:console],
  # compile-time floor: debug-level Logger calls are purged from the release entirely (zero runtime cost, but PROD_LOG_LEVEL=debug can't bring them back — rebuild required). Calls that don't go through Logger macros (e.g. some Untangle paths) aren't affected by purging.
  compile_time_purge_matching: [
    [level_lower_than: :info]
  ],
  # overriden in runtime.exs:
  level: :info

config :bonfire, Bonfire.Web.Endpoint, server: true

config :bonfire, Bonfire.Common.Repo,
  # in releases migrations are not in a flavour-specific directory
  priv: "priv/repo"

# default federating state
config :activity_pub, :instance, federating: false

# config :surface, :compiler, warn_on_undefined_props: false

config :live_view_native_stylesheet,
  annotations: false,
  pretty: false

# temporarily disable the following  
config :bonfire_ui_social, Bonfire.UI.Social.WidgetFeedLive, modularity: :disabled
